export const SHARED_TOKEN_SERVICE = Symbol('SHARED_TOKEN_SERVICE');
export const SHARED_REFRESH_TOKEN_REPOSITORY = Symbol('SHARED_REFRESH_TOKEN_REPOSITORY');

export const SHARED_USER_REPOSITORY = Symbol('SHARED_USER_REPOSITORY');
export const SHARED_ROLE_REPOSITORY = Symbol('SHARED_ROLE_REPOSITORY');
