export const SHARED_TOKEN_SERVICE = Symbol('SHARED_TOKEN_SERVICE');

export const SHARED_USER_REPOSITORY = Symbol('SHARED_USER_REPOSITORY');
export const SHARED_ROLE_REPOSITORY = Symbol('SHARED_ROLE_REPOSITORY');
